#ifndef Constants_h
#define Constants_h

// #define ACTIVE_SERIAL
#ifdef ACTIVE_SERIAL
  // #define ACTIVE_MAIN_SERIAL     //Active detailed print messages
  #define ACTIVE_MAIN_SERIAL_SETUP  //Active setup print messages
  // #define ACTIVE_MAIN_PLOTTER       //Active plotter print messages
  // #define ACTIVE_MAIN_SERIAL_LOGIC  //Active logic print messages
  // #define ACTIVE_BUTTON_RUN_SERIAL
  #define ACTIVE_BUTTON_RUN_SERIAL_SETUP
  // #define ACTIVE_LED_SERIAL
  #define ACTIVE_LED_SERIAL_SETUP
  // #define ACTIVE_TRACKER_SERIAL
  #define ACTIVE_TRACKER_SERIAL_SETUP
  // #define ACTIVE_LASER_SERIAL
  #define ACTIVE_LASER_SERIAL_SETUP
  // #define ACTIVE_LASER_SERIAL_PLOTTER
  // #define ACTIVE_MOTOR_SERIAL
  #define ACTIVE_MOTOR_SERIAL_SETUP
  #define ACTIVE_MOTOR_SERIAL_STEP
#endif

#define ROBOT_STATUS_STOP      0
#define ROBOT_STATUS_RUN       1
#define ROBOT_STATUS_PRE_RUN   2
#define ROBOT_STATUS_POST_RUN  3
#define ROBOT_STATUS_COUNTDOWN 4

// #define INITIAL_DIRECTION_RIGHT
// #define INITIAL_DIRECTION_LEFT 
#define INITIAL_DIRECTION_RANDOM

#define BUTTON_RUN_DELAY_WAITING 1
#define BUTTON_RUN_DELAY_COUNTDOWN 1
#define BUTTON_RUN_DELAY_RUN 10
#define BUTTON_RUN_COUNTDOWN_US 4997000 //997000

// #define ACTIVE_LASER_SENSOR_01 //active laser sensor 01
// #define ACTIVE_LASER_SENSOR_02 //active laser sensor 02
// #define ACTIVE_LASER_SENSOR_03 //active laser sensor 03
// #define ACTIVE_LASER_SENSOR_04 //active laser sensor 04
#define LASER_SENSOR_PIN_XSHUT_01 27 //Pin laser sensor XShut 01
#define LASER_SENSOR_PIN_XSHUT_02 14 //Pin laser sensor XShut 02
#define LASER_SENSOR_PIN_XSHUT_03 4  //Pin laser sensor XShut 03
#define LASER_SENSOR_PIN_XSHUT_04 13 //Pin laser sensor XShut 04
#define LASER_SENSOR_CONTINOUS_READING //Define laser sensor continous reading
#define LASER_SENSOR_HIGH_SPEED //Define laser sensor hih speed
#define LASER_SENSOR_MAX_DISTANCE 350

#define ACTIVE_TRACKER_SENSOR_01 //active tracker sensor 01
#define ACTIVE_TRACKER_SENSOR_02 //active tracker sensor 02
#define TRACKER_ANALOG_UPPER_LIMIT 2600//4095
#define TRACKER_PIN_SENSOR_01 25 //Pin tracker sensor 01
#define TRACKER_PIN_SENSOR_02 26 //Pin tracker sensor 02
#define TRACKER_SENSOR_DELAY_WAITING 100
#define TRACKER_SENSOR_DELAY_PRE_RUN 20
#define TRACKER_SENSOR_DELAY_RUN_MIN 1
#define TRACKER_SENSOR_DELAY_RUN_MAX 3
#define TRACKER_SENSOR_DELAY_RUN_TIME 700


#define BUTTON_RUN_PIN 5

#define LED_PIN_INTERNAL 2
#define LED_PIN_RED 18
#define LED_PIN_YELLOW 19
#define LED_PIN_GREEN 23
#define LED_BLINK_FAST 50
#define LED_BLINK_SLOW 1000

#define ACTIVE_MOTOR_01
#define ACTIVE_MOTOR_02
#define MOTOR_OUTPUT_ESC_01 33 //Signal output pin
#define MOTOR_CHANNEL_ESC_01 1 //lec channel used for generating a pwm signal
#define MOTOR_OUTPUT_ESC_02 32 //Signal output pin
#define MOTOR_CHANNEL_ESC_02 2 //lec channel used for generating a pwm signal
#define MOTOR_MIN_PPM_THOTTLE 1148
#define MOTOR_MAX_PPM_THOTTLE 1832
#define MOTOR_CENTER_PPM_THOTTLE 1488
#define MOTOR_MIN_FORWARD 1511
#define MOTOR_MIN_BACKWARD 1445
#define MOTOR_SPEED_UP 1
#define MOTOR_LINEAR_LIMIT 3000
#define MOTOR_MIDDLE_VALUE 1500
#define MOTOR_MIDDLE_VALUE_SUP 1501
#define MOTOR_MIDDLE_VALUE_INF 1499
#define MOTOR_TOP_VALUE 2000
#define MOTOR_BOTTOM_VALUE 1000
#define MOTOR_DUTY_CICLE_TOP_VALUE 6553
#define MOTOR_DUTY_CICLE_BOTTOM_VALUE 3275
#define MOTOR_DUTY_CICLE_MIDDLE_VALUE 4874
#define MOTOR_DUTY_CICLE_MIN_FORWARD_VALUE 4950
//
#define MOTOR_GRADUAL_US 750
//
#define MOTOR_STOP 1500
#define TRACKER_BORDER_TIME_ROUND 60 //50
#define TRACKER_BORDER_TIME_ROUND_LONG 60 //50
#define MOTOR_SPEED_TRACKER_WHEEL_FAST_SLOWDOWN 80
#define MOTOR_SPEED_TRACKER_WHEEL_FAST 1700
#define MOTOR_SPEED_TRACKER_WHEEL_SLOW 1450
#define MOTOR_SPEED_TRACKER_WHEEL_TURBO_FAST 1300
#define MOTOR_SPEED_TRACKER_WHEEL_TURBO_SLOW 1300
#define MOTOR_SPEED_ATTACK 1700//1700
#define MOTOR_SPEED_LASER_CENTER_WHEEL_FAST 1650
#define MOTOR_SPEED_LASER_CENTER_WHEEL_SLOW 1600
#define MOTOR_SPEED_LASER_LATERAL_WHEEL_FAST 1650
#define MOTOR_SPEED_LASER_LATERAL_WHEEL_SLOW 1600
#define MOTOR_SPEED_SEARCH_WHEEL_FAST 1600
#define MOTOR_SPEED_SEARCH_WHEEL_SLOW 1650

#define TIME_STEP_1 400
#define TIME_STEP_2 1100
#define TIME_STEP_3 1800
#define TIME_STEP_4 2600
#define TIME_STEP_TOP 180000

#define SPEED_STEP_1_FAST 1560
#define SPEED_STEP_1_SLOW 1700
#define SPEED_STEP_2_FAST 1580
#define SPEED_STEP_2_SLOW 1750
#define SPEED_STEP_3_FAST 1600
#define SPEED_STEP_3_SLOW 1800
#define SPEED_STEP_4_FAST 1700
#define SPEED_STEP_4_SLOW 1900

#endif